spring:
  application:
    name: gateway

  data:
    redis:
      cluster:
        nodes:
          - localhost:7001
          - localhost:7002
          - localhost:7003
          - localhost:7004
          - localhost:7005
          - localhost:7006
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  session:
    timeout: 30m

resilience4j:
  retry:
    instances:
      orderApi:  # 이 이름은 @Retry(name = "orderApi")와 매칭됨
        max-attempts: 3         # 최대 3회 재시도
        wait-duration: 1s      # 각 재시도 간 대기 시간 (ISO-8601 또는 s/m/h)
        retry-exceptions:
          - feign.FeignException
          - org.springframework.web.client.HttpServerErrorException
